### ISSUE TITLE
duplicate message being sent on color selection/setting

### ISSUE THREAD

**Issue by tmathmeyer** [Easterlyn/Easterlyn#52]
en_uk version: https://github.com/Easterlyn/Easterlyn/blob/3f78fe67989e149af2e2a73c762976e3534e7316/kitchensink/src/main/java/com/easterlyn/kitchensink/command/ColourCommand.java#L57

is a duplicate of the en_us version sent on line 55.

**Comment by Jikoo** [comment]
Already was fixed https://github.com/Easterlyn/Easterlyn/commit/9c5690e33314103607c427f85f2240ff4535411f#diff-9e2e64b8ef9869df37d03a33c7398c5eL62
